[dpdk] Emit key name in context file as in bfrt and p4info
kamleshbhalui/p4c pull request #11
Opened 2022-04-07 14:20 UTC by kamleshbhalui

2022-04-07 18:08 UTC, usha1830 requested changes
I think some changes might be required in dpdkContext.cpp also to avoid printing "<null>" in the instance or fields name.

Please add some more tests with table without the add_on_miss property.

Is it possible to attach old context json and context json after your changes?

2022-04-07 18:08 UTC, usha1830 commented on testdata/p4_16_samples/pna-dpdk-table-key-use-annon.p4
> +Copyright 2020 Intel Corporation
Copyright 2022

2022-04-11 05:56 UTC, usha1830 approved these changes
LGTM

2022-04-11 07:00 UTC, github-sajan approved these changes
Looks good to me

2022-04-11 07:08 UTC, closed without merging