Flatten local struct in dpdk
kamleshbhalui/p4c pull request #7
Opened 2022-03-02 12:45 UTC by kamleshbhalui

flatten local struct  into metadata struct

2022-03-03 06:49 UTC, usha1830 requested changes
The test looks overly complicated. It would be nice to have a simpler test without vxlan encap/decap and as few actions as possible.

2022-03-03 06:49 UTC, usha1830 commented on backends/dpdk/dpdkArch.cpp
> +            } else if(type->is<IR::Type_Struct>()) {
939-940 can be combined into 
else if (auto strct = ...)

2022-03-03 06:49 UTC, usha1830 commented on backends/dpdk/dpdkArch.cpp
> +    if (expr && expr->expr->toString() == "m")
A single line comment saying this is for flattening nested struct would be helpful here

2022-03-03 08:25 UTC, usha1830 approved these changes
Looks fine.

2022-03-03 08:27 UTC, usha1830 approved these changes

2022-03-03 08:27 UTC, usha1830 commented on testdata/p4_16_samples/psa-dpdk-flatten-local-struct.p4
> +{ bit<16> flex_0; bit<16> flex_1; bit<16> flex_2; bit<16> flex_3; bit<16> flex_4; bit<16> flex_5;}
indentation looks weird. Having the fields on separate lines would be better.

2022-03-03 08:27 UTC, usha1830 commented on testdata/p4_16_samples/psa-dpdk-flatten-local-struct.p4
> +    table vxlan {
table name can be changed to something generic

2022-03-04 04:36 UTC, psivanup approved these changes

2022-03-04 05:30 UTC, closed without merging